'use client';

import { useState, useRef, useEffect } from 'react';
import { PDFDocument } from 'pdf-lib';
import Script from 'next/script';
import Link from 'next/link';
import {
  Upload, FileText, Download, Trash2, Loader2,
  CheckCircle, ShieldCheck, Zap, Globe, ArrowRight,
  TrendingDown, Clock, User, RefreshCw, Lightbulb,
  AlertTriangle, FileSearch,
} from 'lucide-react';
import { Card, CardContent, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { useToast } from '@/hooks/use-toast';

/* ─── Constants ─────────────────────────────────────────────── */
const MAX_SIZE_MB    = 100;
const MAX_SIZE_BYTES = MAX_SIZE_MB * 1024 * 1024;
const LAST_UPDATED   = 'June 2026';
const READ_TIME      = '5 min read';
const REVIEWED_BY    = 'Shubham Gautam';

const formatSize = (bytes: number): string => {
  if (bytes < 1024)             return `${bytes} B`;
  if (bytes < 1024 * 1024)      return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
};

/* ─── Compression levels — unchanged ───────────────────────── */
const COMPRESSION_LEVELS = [
  { value: 1, label: 'Light',   desc: 'Remove metadata only. Fastest, safest. Best for already-small PDFs.',                    color: 'text-green-600', bg: 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800' },
  { value: 2, label: 'Medium',  desc: 'Remove metadata + enable object streams. Best balance of size and quality.',             color: 'text-blue-600',  bg: 'bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800'   },
  { value: 3, label: 'Maximum', desc: 'Full reserialisation. Most aggressive reduction. May take slightly longer.',             color: 'text-red-600',   bg: 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800'       },
];

/* ─── Smart tip based on file size ─────────────────────────── */
function getFileTip(bytes: number): { type: 'info' | 'warn' | 'ok'; msg: string } {
  const mb = bytes / (1024 * 1024);
  if (mb < 0.2) return { type: 'info',  msg: 'This file is already small. Compression gains may be minimal.' };
  if (mb > 20)  return { type: 'warn',  msg: 'Large file detected. For 60–80% reduction, a server-based tool that re-encodes images is needed. Browser compression achieves 5–30%.' };
  return { type: 'ok', msg: 'Good size for browser compression. Medium or Maximum level recommended.' };
}

/* ─── FAQ — single source for schema + render ───────────────── */
const faqItems = [
  { q: 'How does browser-based PDF compression work?',   a: 'TaskGuru uses pdf-lib to parse and reserialise your PDF entirely in your browser. This removes redundant metadata, embedded thumbnails, and unused objects — reducing file size without modifying the actual content or quality.' },
  { q: 'How much will my PDF be compressed?',            a: 'Browser-based compression typically achieves 5–30% reduction. PDFs with large embedded fonts, duplicate objects, or metadata compress the most. Simple text-only PDFs may see smaller reductions.' },
  { q: 'Is my PDF safe to compress here?',               a: 'Yes — 100% safe. Your file never leaves your device. All processing happens locally in your browser using JavaScript. TaskGuru has zero access to your file contents.' },
  { q: 'Will compression affect the quality of my PDF?', a: 'No. This tool removes metadata and redundant data only — it does not re-encode images or change fonts. The visual quality of your PDF remains identical after compression.' },
  { q: 'Why is my compressed file the same size?',       a: 'Some PDFs are already optimised — scanned image PDFs or PDFs generated by modern software may have little redundant data to remove. In this case the file size will remain similar.' },
  { q: 'Can I compress password-protected PDFs?',        a: 'No. Password-protected (encrypted) PDFs cannot be compressed. Remove the password first using TaskGuru\'s free PDF Password Remover tool, then compress.' },
  { q: 'What is the maximum file size I can compress?',  a: 'TaskGuru\'s PDF compressor supports files up to 100MB. For extremely large files, compress them in sections by splitting the PDF first, then compressing each part.' },
];

/* ─── Schemas ─────────────────────────────────────────────── */
const toolSchema = {
  '@context': 'https://schema.org',
  '@type': ['WebApplication', 'SoftwareApplication'],
  name: 'Free PDF Compressor — No Quality Loss | TaskGuru',
  url: 'https://www.taskguru.online/tools/pdf-compressor',
  applicationCategory: 'Utility',
  operatingSystem: 'Any',
  browserRequirements: 'Requires JavaScript',
  description: 'Free browser-based PDF compressor. Reduce PDF file size by removing metadata, duplicate objects, and redundant data. No upload, no watermark, instant download.',
  featureList: [
    'Three compression levels (Light, Medium, Maximum)',
    'Client-side processing — no server upload',
    'No watermark on output',
    'No file size limit up to 100MB',
    'Before/after size comparison',
    'Password-protected PDF detection',
  ],
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD', availability: 'https://schema.org/InStock' },
  publisher: { '@type': 'Organization', name: 'TaskGuru', url: 'https://www.taskguru.online', logo: { '@type': 'ImageObject', url: 'https://www.taskguru.online/logo.png' } },
};

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqItems.map(({ q, a }) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })),
};

const howToSchema = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Compress a PDF for Free Using TaskGuru',
  description: 'Step-by-step guide to reducing PDF file size without quality loss using TaskGuru\'s free browser-based PDF compressor.',
  totalTime: 'PT1M',
  estimatedCost: { '@type': 'MonetaryAmount', currency: 'USD', value: '0' },
  step: [
    { '@type': 'HowToStep', position: 1, name: 'Upload your PDF', text: 'Drag and drop or click to browse your PDF file. Supports up to 100MB.' },
    { '@type': 'HowToStep', position: 2, name: 'Choose compression level', text: 'Select Light (metadata only), Medium (recommended), or Maximum (full reserialisation).' },
    { '@type': 'HowToStep', position: 3, name: 'Click Compress PDF', text: 'The tool processes your file entirely in your browser. No upload occurs.' },
    { '@type': 'HowToStep', position: 4, name: 'Download compressed PDF', text: 'View the before/after size comparison and download your compressed PDF.' },
  ],
};

/* ─── Component ─────────────────────────────────────────────── */
export default function PdfCompressor() {
  const { toast } = useToast();
  const [file, setFile]                     = useState<File | null>(null);
  const [isCompressing, setIsCompressing]   = useState(false);
  const [compressionLevel, setCompressionLevel] = useState(2);
  const [result, setResult] = useState<{
    blob: Blob;
    originalSize: number;
    compressedSize: number;
    savedPercent: number;
  } | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const activeLevel  = COMPRESSION_LEVELS[compressionLevel - 1];
  const fileTip      = file ? getFileTip(file.size) : null;

  /* ── Keyboard shortcut: Enter to compress ── */
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Enter' && file && !result && !isCompressing) {
        e.preventDefault();
        handleCompress();
      }
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [file, result, isCompressing, compressionLevel]);

  /* ── All original logic — unchanged ── */
  const validateAndSetFile = (f: File) => {
    if (f.type !== 'application/pdf') {
      toast({ title: 'Invalid File', description: 'Only PDF files are allowed.', variant: 'destructive' });
      return;
    }
    if (f.size > MAX_SIZE_BYTES) {
      toast({ title: 'File Too Large', description: `Please upload a PDF under ${MAX_SIZE_MB}MB.`, variant: 'destructive' });
      return;
    }
    setFile(f);
    setResult(null);
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selected = e.target.files?.[0];
    if (selected) validateAndSetFile(selected);
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    const dropped = e.dataTransfer.files[0];
    if (dropped) validateAndSetFile(dropped);
  };

  const handleCompress = async () => {
    if (!file) return;
    setIsCompressing(true);
    setResult(null);

    try {
      const arrayBuffer = await file.arrayBuffer();
      const pdfDoc = await PDFDocument.load(arrayBuffer, { updateMetadata: false });

      pdfDoc.setTitle('');
      pdfDoc.setAuthor('');
      pdfDoc.setSubject('');
      pdfDoc.setKeywords([]);
      pdfDoc.setProducer('');
      pdfDoc.setCreator('');

      const useObjectStreams = compressionLevel >= 2;

      if (compressionLevel === 3) {
        const pages = pdfDoc.getPages();
        pages.forEach((page) => page.getSize());
      }

      const compressedBytes = await pdfDoc.save({ useObjectStreams, addDefaultPage: false });
      const originalSize   = file.size;
      const compressedSize = compressedBytes.byteLength;
      const savedPercent   = Math.max(0, Math.round(((originalSize - compressedSize) / originalSize) * 100));
      const blob = new Blob([compressedBytes], { type: 'application/pdf' });
      setResult({ blob, originalSize, compressedSize, savedPercent });

      toast({
        title: 'Compression Complete!',
        description: savedPercent > 0
          ? `Reduced by ${savedPercent}% — saved ${formatSize(originalSize - compressedSize)}`
          : 'File was already optimised — minimal reduction possible.',
      });
    } catch (error) {
      const errMsg     = error instanceof Error ? error.message : '';
      const isEncrypted = errMsg.toLowerCase().includes('encrypt') || errMsg.toLowerCase().includes('password') || errMsg.toLowerCase().includes('decrypt');
      toast({
        title: isEncrypted ? 'Password-Protected PDF' : 'Compression Failed',
        description: isEncrypted
          ? 'This PDF is password-protected. Use the PDF Password Remover first, then try again.'
          : 'Could not process this PDF. Please try a different file.',
        variant: 'destructive',
      });
    } finally {
      setIsCompressing(false);
    }
  };

  const handleDownload = () => {
    if (!result || !file) return;
    const url = URL.createObjectURL(result.blob);
    const a   = document.createElement('a');
    a.href     = url;
    a.download = `compressed-${file.name}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: 'Downloaded!', description: 'Compressed PDF saved to your device.' });
  };

  const handleReset = () => {
    setFile(null);
    setResult(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  return (
    <>
      <Script id="pdf-comp-tool-schema"   type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(toolSchema)  }} />
      <Script id="pdf-comp-faq-schema"    type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema)   }} />
      <Script id="pdf-comp-howto-schema"  type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }} />

      {/* ── EEAT META BAR ── */}
      <div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-muted-foreground border-b border-border pb-4 mb-6">
        <span className="flex items-center gap-1.5"><User className="w-3.5 h-3.5" aria-hidden="true" />Reviewed by <strong className="text-foreground">{REVIEWED_BY}</strong></span>
        <span className="flex items-center gap-1.5"><RefreshCw className="w-3.5 h-3.5" aria-hidden="true" />Updated: <strong className="text-foreground">{LAST_UPDATED}</strong></span>
        <span className="flex items-center gap-1.5"><Clock className="w-3.5 h-3.5" aria-hidden="true" />{READ_TIME}</span>
        <span className="flex items-center gap-x-3 ml-auto">
          <Link href="/privacy-policy" className="hover:text-primary transition-colors">Privacy Policy</Link>
          <span aria-hidden="true">·</span>
          <Link href="/about" className="hover:text-primary transition-colors">About</Link>
          <span aria-hidden="true">·</span>
          <Link href="/contact" className="hover:text-primary transition-colors">Contact</Link>
        </span>
      </div>

      {/* ── QUICK ANSWER ── */}
      <section id="quick-answer" aria-label="Quick Answer" className="p-5 bg-primary/5 border border-primary/20 rounded-2xl mb-6">
        <p className="text-xs font-bold text-primary uppercase tracking-wider mb-2">⚡ Quick Answer</p>
        <p className="text-sm leading-relaxed text-foreground">
          <strong>TaskGuru&apos;s Free PDF Compressor</strong> reduces PDF file size by removing metadata, duplicate objects, and redundant data — entirely in your browser. No file upload, no watermark, no account needed. Choose from three compression levels and download instantly.
        </p>
      </section>

      {/* ── TOOL CARD ── */}
      <Card className="w-full max-w-2xl mx-auto shadow-2xl mt-8 border-2 border-primary/10 rounded-[2rem] bg-white dark:bg-gray-900">
        <CardContent className="p-6 sm:p-10 space-y-6">

          {!file ? (
            <>
              <div
                role="button"
                tabIndex={0}
                aria-label="Upload PDF to compress — drag and drop or click to browse"
                className="flex flex-col items-center justify-center space-y-5 p-10 sm:p-14 border-2 border-dashed border-gray-200 dark:border-gray-700 rounded-[1.5rem] cursor-pointer hover:border-primary/50 hover:bg-gray-50 dark:hover:bg-gray-800 transition-all duration-300"
                onClick={() => fileInputRef.current?.click()}
                onKeyDown={(e) => e.key === 'Enter' && fileInputRef.current?.click()}
                onDragOver={(e) => e.preventDefault()}
                onDrop={handleDrop}
              >
                <div className="p-5 bg-red-50 dark:bg-red-900/20 text-red-500 rounded-full">
                  <Upload className="w-10 h-10" aria-hidden="true" />
                </div>
                <div className="text-center space-y-2">
                  <h3 className="text-xl font-black text-gray-800 dark:text-white">Upload PDF to Compress</h3>
                  <p className="text-gray-500 text-sm font-medium">Drag &amp; Drop or Click to Browse</p>
                  <p className="text-xs text-red-500 font-bold bg-red-50 dark:bg-red-900/20 inline-block px-3 py-1 rounded-full">
                    Max {MAX_SIZE_MB}MB · 100% Private · No Upload
                  </p>
                </div>
                <input
                  ref={fileInputRef}
                  id="pdf-compressor-input"
                  type="file"
                  accept="application/pdf"
                  className="hidden"
                  onChange={handleFileChange}
                  aria-label="Choose PDF file to compress"
                />
              </div>
              <p className="text-center text-xs text-slate-400 dark:text-slate-500">
                ⚠️ Password-protected PDFs cannot be compressed. <Link href="/tools/unlock-pdf-no-upload" className="text-primary hover:underline font-semibold">Remove the password first →</Link>
              </p>
            </>
          ) : (
            <div className="space-y-5">

              {/* File info + page count */}
              <div className="flex items-center gap-4 p-4 bg-gray-50 dark:bg-gray-800 rounded-2xl border border-gray-100 dark:border-gray-700">
                <div className="p-3 bg-red-100 dark:bg-red-900/30 rounded-xl flex-shrink-0">
                  <FileText className="w-6 h-6 text-red-500" aria-hidden="true" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="font-bold text-gray-900 dark:text-white text-sm truncate">{file.name}</p>
                  <p className="text-xs text-gray-500">Original size: <strong>{formatSize(file.size)}</strong></p>
                </div>
              </div>

              {/* Smart file tip */}
              {fileTip && (
                <div className={`flex gap-2 p-3 rounded-xl text-xs leading-relaxed ${
                  fileTip.type === 'warn'
                    ? 'bg-yellow-50 dark:bg-yellow-900/10 border border-yellow-200 text-yellow-700 dark:text-yellow-400'
                    : fileTip.type === 'info'
                    ? 'bg-blue-50 dark:bg-blue-900/10 border border-blue-200 text-blue-700 dark:text-blue-400'
                    : 'bg-green-50 dark:bg-green-900/10 border border-green-200 text-green-700 dark:text-green-400'
                }`}>
                  <Lightbulb className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" aria-hidden="true" />
                  <span>{fileTip.msg}</span>
                </div>
              )}

              {/* Compression Level Selector */}
              {!result && (
                <div className="space-y-4">
                  <div className="flex justify-between items-center">
                    <p className="font-bold text-gray-900 dark:text-white text-sm">
                      Compression Level
                      <span className="ml-2 text-xs font-normal text-gray-400">(Press Enter to compress)</span>
                    </p>
                    <span className={`text-xs font-black px-3 py-1 rounded-full border ${activeLevel.bg} ${activeLevel.color}`}>
                      {activeLevel.label}
                    </span>
                  </div>
                  <Slider
                    min={1} max={3} step={1}
                    value={[compressionLevel]}
                    onValueChange={(v) => { setCompressionLevel(v[0]); setResult(null); }}
                    className="py-2"
                    aria-label={`Compression level: ${activeLevel.label}`}
                  />
                  <div className="flex justify-between text-xs font-bold text-gray-400">
                    <span className="text-green-600">Light</span>
                    <span className="text-blue-600">Medium</span>
                    <span className="text-red-500">Maximum</span>
                  </div>
                  <div className={`p-3 rounded-xl border text-xs leading-relaxed ${activeLevel.bg} ${activeLevel.color}`}>
                    <strong>{activeLevel.label}:</strong> {activeLevel.desc}
                  </div>
                </div>
              )}

              {/* Before / After comparison */}
              {result && (
                <div className="rounded-2xl border-2 border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-900/20 p-5 space-y-4">
                  <div className="flex items-center gap-2">
                    <CheckCircle className="w-5 h-5 text-green-600 dark:text-green-400" aria-hidden="true" />
                    <span className="font-black text-green-700 dark:text-green-300 text-sm uppercase tracking-wider">
                      Compression Complete — {activeLevel.label} Mode
                    </span>
                  </div>
                  <div className="space-y-3">
                    <div className="space-y-1">
                      <div className="flex justify-between text-xs font-bold text-gray-500 dark:text-gray-400">
                        <span>Before</span><span>{formatSize(result.originalSize)}</span>
                      </div>
                      <div className="h-3 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                        <div className="h-full bg-gray-400 dark:bg-gray-500 rounded-full w-full" />
                      </div>
                    </div>
                    <div className="space-y-1">
                      <div className="flex justify-between text-xs font-bold text-gray-500 dark:text-gray-400">
                        <span>After</span><span>{formatSize(result.compressedSize)}</span>
                      </div>
                      <div className="h-3 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                        <div className="h-full bg-green-500 rounded-full transition-all duration-1000" style={{ width: `${Math.max(5, 100 - result.savedPercent)}%` }} />
                      </div>
                    </div>
                  </div>
                  <div className="grid grid-cols-3 gap-3">
                    <div className="text-center p-3 bg-white dark:bg-gray-900 rounded-xl border border-green-100 dark:border-green-900">
                      <p className="text-lg font-black text-green-600 dark:text-green-400" aria-live="polite">{result.savedPercent}%</p>
                      <p className="text-xs text-gray-500 font-medium">Reduced</p>
                    </div>
                    <div className="text-center p-3 bg-white dark:bg-gray-900 rounded-xl border border-green-100 dark:border-green-900">
                      <p className="text-sm font-black text-gray-800 dark:text-white">{formatSize(result.originalSize - result.compressedSize)}</p>
                      <p className="text-xs text-gray-500 font-medium">Saved</p>
                    </div>
                    <div className="text-center p-3 bg-white dark:bg-gray-900 rounded-xl border border-green-100 dark:border-green-900">
                      <p className="text-sm font-black text-gray-800 dark:text-white">{formatSize(result.compressedSize)}</p>
                      <p className="text-xs text-gray-500 font-medium">New Size</p>
                    </div>
                  </div>
                  <button
                    onClick={() => setResult(null)}
                    className="text-xs text-blue-600 dark:text-blue-400 hover:underline font-semibold"
                  >
                    ← Try a different compression level
                  </button>
                </div>
              )}

              {/* Loading */}
              {isCompressing && (
                <div className="flex items-center gap-3 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-2xl border border-blue-100 dark:border-blue-900" role="status" aria-live="polite">
                  <Loader2 className="w-5 h-5 text-blue-600 animate-spin flex-shrink-0" aria-hidden="true" />
                  <div>
                    <p className="text-sm font-bold text-blue-700 dark:text-blue-300">Applying {activeLevel.label} compression...</p>
                    <p className="text-xs text-blue-500 dark:text-blue-400">Your file never leaves your device</p>
                  </div>
                </div>
              )}
            </div>
          )}
        </CardContent>

        {file && (
          <CardFooter className="flex flex-col sm:flex-row justify-center gap-3 bg-gray-50/80 dark:bg-gray-800/50 p-6 border-t rounded-b-[2rem]">
            <Button variant="outline" size="lg" onClick={handleReset} disabled={isCompressing} className="w-full sm:w-auto rounded-xl h-11" aria-label="Remove file and start over">
              <Trash2 className="mr-2 h-4 w-4" aria-hidden="true" /> Change File
            </Button>
            {!result ? (
              <Button size="lg" onClick={handleCompress} disabled={isCompressing || !file} className="w-full sm:w-auto rounded-xl h-11 font-bold shadow-lg shadow-red-500/20" aria-label={`Compress PDF with ${activeLevel.label} compression`}>
                {isCompressing
                  ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden="true" /> Compressing...</>
                  : <><TrendingDown className="mr-2 h-4 w-4" aria-hidden="true" /> Compress PDF</>
                }
              </Button>
            ) : (
              <Button size="lg" onClick={handleDownload} className="w-full sm:w-auto rounded-xl h-11 font-bold bg-green-600 hover:bg-green-700 text-white shadow-lg shadow-green-500/20" aria-label="Download compressed PDF">
                <Download className="mr-2 h-5 w-5" aria-hidden="true" /> Download Compressed PDF
              </Button>
            )}
          </CardFooter>
        )}
      </Card>

      {/* ── SEO ARTICLE ── */}
      <article className="max-w-5xl mx-auto px-6 py-16 space-y-16 text-slate-600 dark:text-slate-400 leading-relaxed">

        <section className="space-y-5">
          <h2 className="text-3xl font-black text-slate-900 dark:text-white">Why Compress a PDF?</h2>
          <p className="text-lg">
            PDF files grow large quickly — especially those with embedded fonts, images, or metadata from multiple editing sessions. Large PDFs cause problems: email attachments get rejected, upload portals have size limits, and storage fills up fast. Compressing removes the bloat without changing your content.
          </p>
          <div className="grid md:grid-cols-3 gap-6">
            {[
              { icon: <ShieldCheck className="w-8 h-8 text-blue-600" aria-hidden="true" />,  title: '100% Private',       desc: 'Your PDF never leaves your browser. All compression happens locally using JavaScript — zero server uploads, zero privacy risk.' },
              { icon: <Zap className="w-8 h-8 text-yellow-500" aria-hidden="true" />,         title: 'Instant Processing', desc: 'No upload queue, no waiting. Compression runs directly on your device and completes in seconds regardless of file size.' },
              { icon: <Globe className="w-8 h-8 text-green-600" aria-hidden="true" />,        title: 'Works Everywhere',   desc: 'Chrome, Safari, Firefox, Edge — on Windows, Mac, Android, and iOS. No software installation required.' },
            ].map((item) => (
              <div key={item.title} className="p-6 bg-slate-50 dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl space-y-3">
                {item.icon}
                <h3 className="font-black text-slate-900 dark:text-white">{item.title}</h3>
                <p className="text-sm">{item.desc}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="space-y-5">
          <h2 className="text-2xl font-black text-slate-900 dark:text-white">Which Compression Level Should I Use?</h2>
          <div className="grid md:grid-cols-3 gap-4">
            {[
              { level: '🟢 Light',   best: 'Already small PDFs, quick cleanup',     what: 'Strips metadata only — author, title, creator tags. Fastest option with zero risk.',                                               reduction: '2–8%',   color: 'border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-900/10' },
              { level: '🔵 Medium',  best: 'Most PDFs — recommended default',       what: 'Metadata removal + object stream merging. Combines duplicate resources into single entries.',                                        reduction: '5–20%',  color: 'border-blue-200 dark:border-blue-800 bg-blue-50 dark:bg-blue-900/10'   },
              { level: '🔴 Maximum', best: 'Large PDFs, heavily edited files',      what: 'Full reserialisation including page-level content stream optimisation. Most aggressive option.',                                     reduction: '10–30%', color: 'border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-900/10'       },
            ].map((item) => (
              <div key={item.level} className={`p-5 border rounded-2xl space-y-3 ${item.color}`}>
                <h3 className="font-black text-slate-900 dark:text-white">{item.level}</h3>
                <p className="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wide">Best for: {item.best}</p>
                <p className="text-sm leading-relaxed">{item.what}</p>
                <div className="pt-1 border-t border-current border-opacity-10">
                  <span className="text-xs font-black">Typical reduction: {item.reduction}</span>
                </div>
              </div>
            ))}
          </div>
          <div className="p-5 bg-yellow-50 dark:bg-yellow-900/20 border-l-4 border-yellow-400 rounded-r-2xl">
            <p className="text-xs font-black text-yellow-700 dark:text-yellow-400 uppercase mb-2">⚠️ Honest Expectation</p>
            <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
              Browser-based compression achieves <strong>2–30% reduction</strong> depending on your PDF type and chosen level. For larger reductions (60–80%), server-based tools that re-encode embedded images are needed. If your PDF is already optimised, all three levels will show minimal reduction — that is normal.
            </p>
          </div>
        </section>

        <section className="space-y-5">
          <h2 className="text-2xl font-black text-slate-900 dark:text-white">How Browser-Based PDF Compression Works</h2>
          <p>TaskGuru uses <strong className="text-slate-800 dark:text-slate-200">pdf-lib</strong> — a pure JavaScript library — to parse and reserialise your PDF directly in your browser. The process removes:</p>
          <div className="grid md:grid-cols-2 gap-4">
            {[
              { item: 'Redundant metadata',  desc: 'Author, creator, producer tags, creation dates — none of which affect the document content.' },
              { item: 'Duplicate objects',   desc: 'PDFs often contain multiple copies of the same resource. Object streams merge these into one.' },
              { item: 'Unused resources',    desc: 'Fonts or images that were referenced but never used in the final layout.' },
              { item: 'Edit history data',   desc: 'PDFs edited multiple times accumulate old version data. Reserialising creates a clean single version.' },
            ].map((item) => (
              <div key={item.item} className="flex gap-3 p-4 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-xl">
                <span className="text-green-500 font-black flex-shrink-0 mt-0.5" aria-hidden="true">✓</span>
                <div>
                  <p className="font-bold text-slate-900 dark:text-white text-sm mb-0.5">{item.item}</p>
                  <p className="text-xs leading-relaxed">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Common Mistakes */}
        <section className="space-y-4">
          <h2 className="text-2xl font-black text-slate-900 dark:text-white flex items-center gap-2">
            <AlertTriangle className="w-6 h-6 text-yellow-500" aria-hidden="true" /> Common PDF Compression Mistakes
          </h2>
          <div className="space-y-3">
            {[
              { m: 'Using Maximum level on small PDFs',          f: 'If your PDF is under 500KB, Light or Medium compression is sufficient. Maximum mode takes longer with negligible additional benefit.' },
              { m: 'Expecting 80%+ reduction from browser tools', f: 'Browser tools remove structural bloat. Server-based tools that re-encode embedded images achieve larger reductions. Understand the difference.' },
              { m: 'Compressing password-protected PDFs',         f: 'Remove the password first using the PDF Password Remover, then compress the unlocked version.' },
              { m: 'Not verifying the output after compression',  f: 'Always open the downloaded compressed PDF to confirm all pages and content look correct before sharing or submitting.' },
            ].map((item) => (
              <div key={item.m} className="flex gap-3 p-4 bg-yellow-50 dark:bg-yellow-900/10 border border-yellow-200 dark:border-yellow-800/50 rounded-xl text-sm">
                <AlertTriangle className="w-4 h-4 text-yellow-500 shrink-0 mt-0.5" aria-hidden="true" />
                <div>
                  <p className="font-bold text-slate-900 dark:text-white">❌ {item.m}</p>
                  <p className="mt-0.5">✅ {item.f}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Summary */}
        <section id="tool-summary" className="p-6 bg-primary/5 border border-primary/20 rounded-2xl">
          <h2 className="text-xl font-black text-slate-900 dark:text-white mb-4">Summary</h2>
          <ul className="space-y-2 text-sm" role="list">
            {[
              'Reduces PDF size by removing metadata, duplicate objects, and edit history.',
              'Three levels: Light (2–8%), Medium (5–20%), Maximum (10–30%).',
              '100% browser-based — your file never leaves your device.',
              'No watermark, no account, no file size limit up to 100MB.',
              'Password-protected PDFs cannot be compressed — remove password first.',
              'Press Enter after uploading to compress immediately.',
            ].map((point) => (
              <li key={point} className="flex items-start gap-2">
                <CheckCircle className="w-4 h-4 text-primary shrink-0 mt-0.5" aria-hidden="true" />
                <span>{point}</span>
              </li>
            ))}
          </ul>
        </section>

        {/* FAQ */}
        <section className="space-y-5">
          <h2 className="text-2xl font-black text-slate-900 dark:text-white">Frequently Asked Questions</h2>
          <div className="space-y-3">
            {faqItems.map((faq, i) => (
              <details key={i} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-2xl p-5 cursor-pointer group">
                <summary className="font-bold text-slate-900 dark:text-white list-none flex justify-between items-center text-sm">
                  {faq.q}
                  <span className="transition-transform group-open:rotate-180 text-slate-400 flex-shrink-0 ml-2" aria-hidden="true">▼</span>
                </summary>
                <p className="mt-3 text-sm leading-relaxed">{faq.a}</p>
              </details>
            ))}
          </div>
        </section>

        {/* Related Tools — 10+ verified links */}
        <section className="border-t border-slate-100 dark:border-slate-800 pt-12 space-y-6">
          <h3 className="text-xl font-black text-slate-900 dark:text-white">Related PDF Tools</h3>
          <div className="grid md:grid-cols-2 gap-4">
            {[
              { label: 'Merge PDF Files',       sub: 'Combine multiple PDFs into one',         href: '/tools/merge-pdf',              color: 'hover:border-orange-400' }, // ✅
              { label: 'Split PDF Pages',       sub: 'Extract individual pages from a PDF',    href: '/tools/split-pdf',             color: 'hover:border-purple-400' }, // ✅
              { label: 'PDF to Word',           sub: 'Convert PDF to editable .docx',          href: '/tools/pdf-to-word',           color: 'hover:border-blue-400'   }, // ✅
              { label: 'Image to PDF',          sub: 'Convert JPG & PNG to PDF',               href: '/tools/image-to-pdf',          color: 'hover:border-green-400'  }, // ✅
              { label: 'PDF Editor Pro',        sub: 'Add text, erase, and edit PDFs',         href: '/tools/pdf-editor-pro',        color: 'hover:border-indigo-400' }, // ✅
              { label: 'PDF Password Remover',  sub: 'Unlock encrypted PDFs',                  href: '/tools/unlock-pdf-no-upload',  color: 'hover:border-yellow-400' }, // ✅
              { label: 'PDF Redactor',          sub: 'Black-box redact sensitive content',     href: '/tools/pdf-redactor',          color: 'hover:border-red-400'    }, // ✅
              { label: 'E-Sign PDF',            sub: 'Add digital signature to PDF',           href: '/tools/esign-pdf-no-upload',   color: 'hover:border-pink-400'   }, // ✅
              { label: 'Excel to PDF',          sub: 'Convert spreadsheets to PDF',            href: '/tools/excel-to-pdf',          color: 'hover:border-teal-400'   }, // ✅
              { label: 'Word to PDF',           sub: 'Convert Word documents to PDF',          href: '/tools/word-to-pdf',           color: 'hover:border-cyan-400'   }, // ✅
            ].map((tool) => (
              <Link key={tool.href} href={tool.href}
                className={`flex items-center justify-between p-5 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 ${tool.color} rounded-2xl transition-colors group`}
                aria-label={`${tool.label} — ${tool.sub}`}
              >
                <div>
                  <p className="font-bold text-slate-900 dark:text-white text-sm">{tool.label}</p>
                  <p className="text-xs text-slate-500">{tool.sub}</p>
                </div>
                <ArrowRight className="w-4 h-4 text-slate-300 group-hover:text-slate-600 dark:group-hover:text-slate-300 transition-colors flex-shrink-0" aria-hidden="true" />
              </Link>
            ))}
          </div>
          {/* Blog links */}
          <div className="p-5 rounded-xl border bg-slate-50 dark:bg-slate-900 space-y-2">
            <p className="font-bold text-slate-900 dark:text-white text-sm">Related Reading</p>
            {[
              { href: '/blog/how-to-compress-pdf-free',              title: 'How to Compress a PDF for Free — Complete Guide'      }, // ✅
              { href: '/blog/how-to-compress-images-without-losing-quality', title: 'How to Compress Images Without Losing Quality' }, // ✅
              { href: '/blog/free-online-tools-students-2026-no-login', title: 'Best Free Tools for Students 2026'                 }, // ✅
            ].map((post) => (
              <Link key={post.href} href={post.href} className="flex items-center gap-2 text-sm text-primary hover:underline" aria-label={post.title}>
                <ArrowRight className="w-3.5 h-3.5 shrink-0" aria-hidden="true" />{post.title}
              </Link>
            ))}
          </div>
        </section>

      </article>
    </>
  );
}
