'use client';

import { useState, useRef } from 'react';
import { PDFDocument } from 'pdf-lib';
import Link from 'next/link';
import {
  Upload, FileText, Download, Trash2, Loader2,
  CheckCircle, ShieldCheck, Zap, Globe, HelpCircle,
  ArrowRight, TrendingDown,
} from 'lucide-react';
import { Card, CardContent, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { useToast } from '@/hooks/use-toast';

const MAX_SIZE_MB = 100;
const MAX_SIZE_BYTES = MAX_SIZE_MB * 1024 * 1024;

const formatSize = (bytes: number): string => {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
};

// ✅ Compression level definitions
const COMPRESSION_LEVELS = [
  {
    value: 1,
    label: 'Light',
    desc: 'Remove metadata only. Fastest, safest. Best for already-small PDFs.',
    color: 'text-green-600',
    bg: 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800',
  },
  {
    value: 2,
    label: 'Medium',
    desc: 'Remove metadata + enable object streams. Best balance of size and quality.',
    color: 'text-blue-600',
    bg: 'bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800',
  },
  {
    value: 3,
    label: 'Maximum',
    desc: 'Full reserialisation. Most aggressive reduction. May take slightly longer.',
    color: 'text-red-600',
    bg: 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800',
  },
];

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'How does browser-based PDF compression work?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'TaskGuru uses pdf-lib to parse and reserialise your PDF entirely in your browser. This removes redundant metadata, embedded thumbnails, and unused objects — reducing file size without modifying the actual content or quality.',
      },
    },
    {
      '@type': 'Question',
      name: 'How much will my PDF be compressed?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Browser-based compression typically achieves 5–30% reduction. PDFs with large embedded fonts, duplicate objects, or metadata compress the most. Simple text-only PDFs may see smaller reductions.',
      },
    },
    {
      '@type': 'Question',
      name: 'Is my PDF safe to compress here?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes — 100% safe. Your file never leaves your device. All processing happens locally in your browser using JavaScript. TaskGuru has zero access to your file contents.',
      },
    },
    {
      '@type': 'Question',
      name: 'Will compression affect the quality of my PDF?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'No. This tool removes metadata and redundant data only — it does not re-encode images or change fonts. The visual quality of your PDF remains identical after compression.',
      },
    },
    {
      '@type': 'Question',
      name: 'Why is my compressed file the same size?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Some PDFs are already optimised — scanned image PDFs or PDFs generated by modern software may have little redundant data to remove. In this case the file size will remain similar.',
      },
    },
  ],
};

export default function PdfCompressor() {
  const { toast } = useToast();
  const [file, setFile] = useState<File | null>(null);
  const [isCompressing, setIsCompressing] = useState(false);
  const [compressionLevel, setCompressionLevel] = useState(2); // default: Medium
  const [result, setResult] = useState<{
    blob: Blob;
    originalSize: number;
    compressedSize: number;
    savedPercent: number;
  } | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const activeLevel = COMPRESSION_LEVELS[compressionLevel - 1];

  const validateAndSetFile = (f: File) => {
    if (f.type !== 'application/pdf') {
      toast({ title: 'Invalid File', description: 'Only PDF files are allowed.', variant: 'destructive' });
      return;
    }
    if (f.size > MAX_SIZE_BYTES) {
      toast({ title: 'File Too Large', description: `Please upload a PDF under ${MAX_SIZE_MB}MB.`, variant: 'destructive' });
      return;
    }
    setFile(f);
    setResult(null);
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selected = e.target.files?.[0];
    if (selected) validateAndSetFile(selected);
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    const dropped = e.dataTransfer.files[0];
    if (dropped) validateAndSetFile(dropped);
  };

  const handleCompress = async () => {
    if (!file) return;
    setIsCompressing(true);
    setResult(null);

    try {
      const arrayBuffer = await file.arrayBuffer();
      const pdfDoc = await PDFDocument.load(arrayBuffer, {
        updateMetadata: false,
      });

      // Level 1, 2, 3: always strip metadata
      pdfDoc.setTitle('');
      pdfDoc.setAuthor('');
      pdfDoc.setSubject('');
      pdfDoc.setKeywords([]);
      pdfDoc.setProducer('');
      pdfDoc.setCreator('');

      // Level 2+: use object streams (merges duplicate objects)
      const useObjectStreams = compressionLevel >= 2;

      // Level 3: additional page-level reserialisation pass
      if (compressionLevel === 3) {
        const pages = pdfDoc.getPages();
        // Trigger re-encoding of page content streams
        pages.forEach((page) => {
          // Access page dict to force reserialisation
          page.node.normalizeContents();
        });
      }

      const compressedBytes = await pdfDoc.save({
        useObjectStreams,
        addDefaultPage: false,
      });

      const originalSize = file.size;
      const compressedSize = compressedBytes.byteLength;
      const savedPercent = Math.max(
        0,
        Math.round(((originalSize - compressedSize) / originalSize) * 100)
      );

      const blob = new Blob([compressedBytes], { type: 'application/pdf' });
      setResult({ blob, originalSize, compressedSize, savedPercent });

      toast({
        title: 'Compression Complete!',
        description: savedPercent > 0
          ? `Reduced by ${savedPercent}% — saved ${formatSize(originalSize - compressedSize)}`
          : 'File was already optimised — minimal reduction possible.',
      });
    } catch (error) {
      console.error(error);
      toast({
        title: 'Compression Failed',
        description: 'Could not process this PDF. Is it password-protected?',
        variant: 'destructive',
      });
    } finally {
      setIsCompressing(false);
    }
  };

  const handleDownload = () => {
    if (!result || !file) return;
    const url = URL.createObjectURL(result.blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `compressed-${file.name}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: 'Downloaded!', description: 'Compressed PDF saved to your device.' });
  };

  const handleReset = () => {
    setFile(null);
    setResult(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      {/* ── TOOL CARD ── */}
      <Card className="w-full max-w-2xl mx-auto shadow-2xl mt-8 border-2 border-primary/10 rounded-[2rem] bg-white dark:bg-gray-900">
        <CardContent className="p-6 sm:p-10 space-y-6">

          {/* Upload area */}
          {!file ? (
            <div
              className="flex flex-col items-center justify-center space-y-5 p-10 sm:p-14 border-2 border-dashed border-gray-200 dark:border-gray-700 rounded-[1.5rem] cursor-pointer hover:border-primary/50 hover:bg-gray-50 dark:hover:bg-gray-800 transition-all duration-300"
              onClick={() => fileInputRef.current?.click()}
              onDragOver={(e) => e.preventDefault()}
              onDrop={handleDrop}
            >
              <div className="p-5 bg-red-50 dark:bg-red-900/20 text-red-500 rounded-full">
                <Upload className="w-10 h-10" />
              </div>
              <div className="text-center space-y-2">
                <h3 className="text-xl font-black text-gray-800 dark:text-white">
                  Upload PDF to Compress
                </h3>
                <p className="text-gray-500 text-sm font-medium">
                  Drag & Drop or Click to Browse
                </p>
                <p className="text-xs text-red-500 font-bold bg-red-50 dark:bg-red-900/20 inline-block px-3 py-1 rounded-full">
                  Max {MAX_SIZE_MB}MB · 100% Private · No Upload
                </p>
              </div>
              <input
                ref={fileInputRef}
                type="file"
                accept="application/pdf"
                className="hidden"
                onChange={handleFileChange}
              />
            </div>
          ) : (
            <div className="space-y-5">

              {/* File info */}
              <div className="flex items-center gap-4 p-4 bg-gray-50 dark:bg-gray-800 rounded-2xl border border-gray-100 dark:border-gray-700">
                <div className="p-3 bg-red-100 dark:bg-red-900/30 rounded-xl flex-shrink-0">
                  <FileText className="w-6 h-6 text-red-500" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="font-bold text-gray-900 dark:text-white text-sm truncate">{file.name}</p>
                  <p className="text-xs text-gray-500">Original size: <strong>{formatSize(file.size)}</strong></p>
                </div>
              </div>

              {/* ✅ Compression Level Selector */}
              {!result && (
                <div className="space-y-4">
                  <div className="flex justify-between items-center">
                    <p className="font-bold text-gray-900 dark:text-white text-sm">
                      Compression Level
                    </p>
                    <span className={`text-xs font-black px-3 py-1 rounded-full border ${activeLevel.bg} ${activeLevel.color}`}>
                      {activeLevel.label}
                    </span>
                  </div>

                  {/* Slider */}
                  <Slider
                    min={1}
                    max={3}
                    step={1}
                    value={[compressionLevel]}
                    onValueChange={(v) => {
                      setCompressionLevel(v[0]);
                      setResult(null);
                    }}
                    className="py-2"
                  />

                  {/* Level labels */}
                  <div className="flex justify-between text-xs font-bold text-gray-400">
                    <span className="text-green-600">Light</span>
                    <span className="text-blue-600">Medium</span>
                    <span className="text-red-500">Maximum</span>
                  </div>

                  {/* Active level description */}
                  <div className={`p-3 rounded-xl border text-xs leading-relaxed ${activeLevel.bg} ${activeLevel.color}`}>
                    <strong>{activeLevel.label}:</strong> {activeLevel.desc}
                  </div>
                </div>
              )}

              {/* Before / After comparison */}
              {result && (
                <div className="rounded-2xl border-2 border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-900/20 p-5 space-y-4">
                  <div className="flex items-center gap-2">
                    <CheckCircle className="w-5 h-5 text-green-600 dark:text-green-400" />
                    <span className="font-black text-green-700 dark:text-green-300 text-sm uppercase tracking-wider">
                      Compression Complete — {activeLevel.label} Mode
                    </span>
                  </div>

                  {/* Size bars */}
                  <div className="space-y-3">
                    <div className="space-y-1">
                      <div className="flex justify-between text-xs font-bold text-gray-500 dark:text-gray-400">
                        <span>Before</span>
                        <span>{formatSize(result.originalSize)}</span>
                      </div>
                      <div className="h-3 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                        <div className="h-full bg-gray-400 dark:bg-gray-500 rounded-full w-full" />
                      </div>
                    </div>
                    <div className="space-y-1">
                      <div className="flex justify-between text-xs font-bold text-gray-500 dark:text-gray-400">
                        <span>After</span>
                        <span>{formatSize(result.compressedSize)}</span>
                      </div>
                      <div className="h-3 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                        <div
                          className="h-full bg-green-500 rounded-full transition-all duration-1000"
                          style={{ width: `${Math.max(5, 100 - result.savedPercent)}%` }}
                        />
                      </div>
                    </div>
                  </div>

                  {/* Stats */}
                  <div className="grid grid-cols-3 gap-3">
                    <div className="text-center p-3 bg-white dark:bg-gray-900 rounded-xl border border-green-100 dark:border-green-900">
                      <p className="text-lg font-black text-green-600 dark:text-green-400">
                        {result.savedPercent}%
                      </p>
                      <p className="text-xs text-gray-500 font-medium">Reduced</p>
                    </div>
                    <div className="text-center p-3 bg-white dark:bg-gray-900 rounded-xl border border-green-100 dark:border-green-900">
                      <p className="text-sm font-black text-gray-800 dark:text-white">
                        {formatSize(result.originalSize - result.compressedSize)}
                      </p>
                      <p className="text-xs text-gray-500 font-medium">Saved</p>
                    </div>
                    <div className="text-center p-3 bg-white dark:bg-gray-900 rounded-xl border border-green-100 dark:border-green-900">
                      <p className="text-sm font-black text-gray-800 dark:text-white">
                        {formatSize(result.compressedSize)}
                      </p>
                      <p className="text-xs text-gray-500 font-medium">New Size</p>
                    </div>
                  </div>

                  {/* Try different level */}
                  <button
                    onClick={() => setResult(null)}
                    className="text-xs text-blue-600 dark:text-blue-400 hover:underline font-semibold"
                  >
                    ← Try a different compression level
                  </button>
                </div>
              )}

              {/* Loading */}
              {isCompressing && (
                <div className="flex items-center gap-3 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-2xl border border-blue-100 dark:border-blue-900">
                  <Loader2 className="w-5 h-5 text-blue-600 animate-spin flex-shrink-0" />
                  <div>
                    <p className="text-sm font-bold text-blue-700 dark:text-blue-300">
                      Applying {activeLevel.label} compression...
                    </p>
                    <p className="text-xs text-blue-500 dark:text-blue-400">
                      Your file never leaves your device
                    </p>
                  </div>
                </div>
              )}
            </div>
          )}
        </CardContent>

        {file && (
          <CardFooter className="flex flex-col sm:flex-row justify-center gap-3 bg-gray-50/80 dark:bg-gray-800/50 p-6 border-t rounded-b-[2rem]">
            <Button
              variant="outline" size="lg"
              onClick={handleReset}
              disabled={isCompressing}
              className="w-full sm:w-auto rounded-xl h-11"
            >
              <Trash2 className="mr-2 h-4 w-4" /> Change File
            </Button>

            {!result ? (
              <Button
                size="lg"
                onClick={handleCompress}
                disabled={isCompressing || !file}
                className="w-full sm:w-auto rounded-xl h-11 font-bold shadow-lg shadow-red-500/20"
              >
                {isCompressing
                  ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Compressing...</>
                  : <><TrendingDown className="mr-2 h-4 w-4" /> Compress PDF</>
                }
              </Button>
            ) : (
              <Button
                size="lg"
                onClick={handleDownload}
                className="w-full sm:w-auto rounded-xl h-11 font-bold bg-green-600 hover:bg-green-700 text-white shadow-lg shadow-green-500/20"
              >
                <Download className="mr-2 h-5 w-5" /> Download Compressed PDF
              </Button>
            )}
          </CardFooter>
        )}
      </Card>

      {/* ── SEO ARTICLE ── */}
      <article className="max-w-5xl mx-auto px-6 py-16 space-y-16 text-slate-600 dark:text-slate-400 leading-relaxed">

        <section className="space-y-5">
          <h2 className="text-3xl font-black text-slate-900 dark:text-white">
            Why Compress a PDF?
          </h2>
          <p className="text-lg">
            PDF files grow large quickly — especially those with embedded fonts, images,
            or metadata from multiple editing sessions. Large PDFs cause problems: email
            attachments get rejected, upload portals have size limits, and storage fills
            up fast. Compressing removes the bloat without changing your content.
          </p>
          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                icon: <ShieldCheck className="w-8 h-8 text-blue-600" />,
                title: '100% Private',
                desc: 'Your PDF never leaves your browser. All compression happens locally using JavaScript — zero server uploads, zero privacy risk.',
              },
              {
                icon: <Zap className="w-8 h-8 text-yellow-500" />,
                title: 'Instant Processing',
                desc: 'No upload queue, no waiting. Compression runs directly on your device and completes in seconds regardless of file size.',
              },
              {
                icon: <Globe className="w-8 h-8 text-green-600" />,
                title: 'Works Everywhere',
                desc: 'Chrome, Safari, Firefox, Edge — on Windows, Mac, Android, and iOS. No software installation required.',
              },
            ].map((item) => (
              <div key={item.title} className="p-6 bg-slate-50 dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl space-y-3">
                {item.icon}
                <h3 className="font-black text-slate-900 dark:text-white">{item.title}</h3>
                <p className="text-sm">{item.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Compression levels explained */}
        <section className="space-y-5">
          <h2 className="text-2xl font-black text-slate-900 dark:text-white">
            Which Compression Level Should I Use?
          </h2>
          <div className="grid md:grid-cols-3 gap-4">
            {[
              {
                level: '🟢 Light',
                best: 'Already small PDFs, quick cleanup',
                what: 'Strips metadata only — author, title, creator tags. Fastest option with zero risk.',
                reduction: '2–8%',
                color: 'border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-900/10',
              },
              {
                level: '🔵 Medium',
                best: 'Most PDFs — recommended default',
                what: 'Metadata removal + object stream merging. Combines duplicate resources into single entries.',
                reduction: '5–20%',
                color: 'border-blue-200 dark:border-blue-800 bg-blue-50 dark:bg-blue-900/10',
              },
              {
                level: '🔴 Maximum',
                best: 'Large PDFs, heavily edited files',
                what: 'Full reserialisation including page-level content stream optimisation. Most aggressive option.',
                reduction: '10–30%',
                color: 'border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-900/10',
              },
            ].map((item) => (
              <div key={item.level} className={`p-5 border rounded-2xl space-y-3 ${item.color}`}>
                <h3 className="font-black text-slate-900 dark:text-white">{item.level}</h3>
                <p className="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wide">
                  Best for: {item.best}
                </p>
                <p className="text-sm leading-relaxed">{item.what}</p>
                <div className="pt-1 border-t border-current border-opacity-10">
                  <span className="text-xs font-black">Typical reduction: {item.reduction}</span>
                </div>
              </div>
            ))}
          </div>
          <div className="p-5 bg-yellow-50 dark:bg-yellow-900/20 border-l-4 border-yellow-400 rounded-r-2xl">
            <p className="text-xs font-black text-yellow-700 dark:text-yellow-400 uppercase mb-2">⚠️ Honest Expectation</p>
            <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
              Browser-based compression achieves <strong>2–30% reduction</strong> depending
              on your PDF type and chosen level. For larger reductions (60–80%),
              server-based tools that re-encode embedded images are needed. If your PDF
              is already optimised, all three levels will show minimal reduction — that is normal.
            </p>
          </div>
        </section>

        <section className="space-y-5">
          <h2 className="text-2xl font-black text-slate-900 dark:text-white">
            How Browser-Based PDF Compression Works
          </h2>
          <p>
            TaskGuru uses{' '}
            <strong className="text-slate-800 dark:text-slate-200">pdf-lib</strong> — a
            pure JavaScript library — to parse and reserialise your PDF directly in
            your browser. The process removes:
          </p>
          <div className="grid md:grid-cols-2 gap-4">
            {[
              { item: 'Redundant metadata', desc: 'Author, creator, producer tags, creation dates — none of which affect the document content.' },
              { item: 'Duplicate objects', desc: 'PDFs often contain multiple copies of the same resource. Object streams merge these into one.' },
              { item: 'Unused resources', desc: 'Fonts or images that were referenced but never used in the final layout.' },
              { item: 'Edit history data', desc: 'PDFs edited multiple times accumulate old version data. Reserialising creates a clean single version.' },
            ].map((item) => (
              <div key={item.item} className="flex gap-3 p-4 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-xl">
                <span className="text-green-500 font-black flex-shrink-0 mt-0.5">✓</span>
                <div>
                  <p className="font-bold text-slate-900 dark:text-white text-sm mb-0.5">{item.item}</p>
                  <p className="text-xs leading-relaxed">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="space-y-5">
          <h2 className="text-2xl font-black text-slate-900 dark:text-white flex items-center gap-2">
            <HelpCircle className="w-6 h-6 text-blue-600" /> Frequently Asked Questions
          </h2>
          <div className="space-y-3">
            {faqSchema.mainEntity.map((faq, i) => (
              <details
                key={i}
                className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-2xl p-5 cursor-pointer group"
              >
                <summary className="font-bold text-slate-900 dark:text-white list-none flex justify-between items-center text-sm">
                  {faq.name}
                  <span className="transition-transform group-open:rotate-180 text-slate-400 flex-shrink-0 ml-2">▼</span>
                </summary>
                <p className="mt-3 text-sm leading-relaxed">{faq.acceptedAnswer.text}</p>
              </details>
            ))}
          </div>
        </section>

        <section className="border-t border-slate-100 dark:border-slate-800 pt-12 space-y-6">
          <h3 className="text-xl font-black text-slate-900 dark:text-white">Related PDF Tools</h3>
          <div className="grid md:grid-cols-2 gap-4">
            {[
              { label: 'Merge PDF Files', sub: 'Combine multiple PDFs into one', href: '/tools/merge-pdf', color: 'hover:border-orange-400' },
              { label: 'Split PDF Pages', sub: 'Extract individual pages from a PDF', href: '/tools/split-pdf', color: 'hover:border-purple-400' },
              { label: 'PDF to Word Converter', sub: 'Convert PDF to editable .docx', href: '/tools/pdf-to-word', color: 'hover:border-blue-400' },
              { label: 'Image to PDF', sub: 'Convert JPG & PNG to PDF', href: '/tools/image-to-pdf', color: 'hover:border-green-400' },
            ].map((tool) => (
              <Link
                key={tool.href}
                href={tool.href}
                className={`flex items-center justify-between p-5 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 ${tool.color} rounded-2xl transition-colors group`}
              >
                <div>
                  <p className="font-bold text-slate-900 dark:text-white text-sm">{tool.label}</p>
                  <p className="text-xs text-slate-500">{tool.sub}</p>
                </div>
                <ArrowRight className="w-4 h-4 text-slate-300 group-hover:text-slate-600 dark:group-hover:text-slate-300 transition-colors flex-shrink-0" />
              </Link>
            ))}
          </div>
        </section>

      </article>
    </>
  );
}
