import React from 'react';
import Link from 'next/link';
import type { Metadata } from 'next';
import { Scale, ShieldAlert, Gavel, FileText, Mail, Info } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service | TaskGuru (Toolify) Usage Policy',
  description: 'Read the official Terms of Service for TaskGuru (Toolify). Understand our rules for acceptable use, intellectual property, and limitation of liability.',
  alternates: {
    canonical: 'https://www.taskguru.online/terms',
  },
};

export default function TermsPage() {
  return (
    <main className="p-6 max-w-4xl mx-auto py-16 min-h-screen">
      
      {/* HEADER SECTION */}
      <div className="text-center mb-12">
        <div className="inline-flex items-center justify-center p-3 bg-primary/10 rounded-full mb-4">
          <Scale className="w-8 h-8 text-primary" />
        </div>
        <h1 className="text-4xl font-black mb-4 tracking-tight text-gray-900 dark:text-white">
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground uppercase tracking-widest font-bold">
          Effective Date: October 30, 2025
        </p>
      </div>

      <div className="space-y-10 text-lg leading-relaxed text-gray-700 dark:text-gray-300">
        
        <p className="bg-muted/50 p-6 rounded-2xl border-l-4 border-primary italic font-medium">
          By accessing or using TaskGuru (also known as Toolify), you agree to be bound by these Terms of Service. These rules govern your use of our digital toolkit. If you disagree with any part of these terms, please discontinue use of the website immediately.
        </p>

        {/* 1. Acceptable Use */}
        <section>
          <h2 className="text-2xl font-bold mb-4 flex items-center gap-2 text-gray-900 dark:text-white">
            <ShieldAlert className="w-6 h-6 text-primary" /> 1. Acceptable Use
          </h2>
          <p className="mb-4">
            You agree to use our services only for lawful, ethical purposes. You shall not upload, post, or transmit any content that:
          </p>
          <ul className="list-disc list-inside ml-4 space-y-3 marker:text-primary">
            <li>Is unlawful, harmful, threatening, harassing, or promotes hate speech.</li>
            <li>Infringes upon any copyright, trademark, or other intellectual property rights.</li>
            <li>Contains spam, viruses, or any other malicious code intended to damage the site or its users.</li>
            <li>Attempts to reverse-engineer or scrape the platform for commercial purposes.</li>
          </ul>
        </section>

        {/* 2. Intellectual Property */}
        <section>
          <h2 className="text-2xl font-bold mb-4 flex items-center gap-2 text-gray-900 dark:text-white">
            <Gavel className="w-6 h-6 text-primary" /> 2. Intellectual Property Rights
          </h2>
          <p className="mb-4">
            The website design, original content, tool interfaces, and source code are the sole property of TaskGuru and are protected by international copyright laws.
          </p>
          <ul className="list-disc list-inside ml-4 space-y-3 marker:text-primary">
            <li><strong>User Content:</strong> You retain all ownership rights to the files you upload. TaskGuru is granted a limited, temporary license to process that material solely to provide the service.</li>
            <li><strong>AI/Tool Outputs:</strong> You are entirely responsible for the use of any text, images, or outputs generated by our tools and any legal consequences arising therefrom.</li>
          </ul>
        </section>
        
        {/* 3. Termination and Changes */}
        <section>
          <h2 className="text-2xl font-bold mb-4 flex items-center gap-2 text-gray-900 dark:text-white">
            <FileText className="w-6 h-6 text-primary" /> 3. Service Changes & Termination
          </h2>
          <p className="mb-6">
            TaskGuru reserves the right to add, modify, or discontinue any of its services (such as specific tool functionality) at any time without prior notice. We may suspend or terminate access for any user found in violation of these terms.
          </p>
        </section>

        {/* 4. Limitation of Liability (CRITICAL) */}
        <section className="bg-red-50 dark:bg-red-900/10 p-8 rounded-[2rem] border border-red-200 dark:border-red-900/30">
          <h2 className="text-2xl font-bold mb-4 flex items-center gap-2 text-red-700 dark:text-red-400">
            <ShieldAlert className="w-6 h-6" /> 4. Disclaimer & Limitation of Liability
          </h2>
          <p className="mb-4 font-medium">
            Our services are provided on an "AS IS" and "AS AVAILABLE" basis. TaskGuru makes no warranties that the services will be uninterrupted, secure, or error-free.
          </p>
          <p className="text-red-800 dark:text-red-300 italic text-sm">
            <strong>Limitation of Liability:</strong> Under no circumstances shall TaskGuru, or its founder Shubham Gautam, be liable for any direct, indirect, or incidental damages resulting from the use or misuse of the services. Use of the platform is entirely at your own risk.
          </p>
        </section>

        {/* 5. Contact Info */}
        <section className="pt-8 border-t border-border">
          <h2 className="text-2xl font-bold mb-4 flex items-center gap-2 text-gray-900 dark:text-white">
            <Mail className="w-6 h-6 text-primary" /> 5. Contact Us
          </h2>
          <p className="mb-4">
            If you have questions regarding these Terms of Service, please reach out to us via the contact details below.
          </p>
          <div className="flex flex-col sm:flex-row justify-center gap-6 p-6 bg-muted rounded-2xl">
            <p className="font-bold">Email: <a href="mailto:gautamshubham962@gmail.com" className="text-primary hover:underline">gautamshubham962@gmail.com</a></p>
            <p className="font-bold">Website: <Link href="/" className="text-primary hover:underline">https://taskguru.online</Link></p>
          </div>
        </section>

      </div>
      
      <footer className="mt-16 text-center text-sm text-muted-foreground italic">
        Last updated: October 30, 2025. TaskGuru (Toolify) – Built for a Productive Web.
      </footer>
    </main>
  );
}

