// src/app/blog/what-is-a-qr-code/page.tsx
import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'What is a QR Code? Create One Free in 30 Seconds (2026 Guide) | TaskGuru',
  description:
    'What is a QR code and how does it work? Learn in simple terms and create your own QR code free in 30 seconds. No signup, no watermark.',
  alternates: {
    canonical: 'https://www.taskguru.online/blog/what-is-a-qr-code',
  },
  openGraph: {
    title: 'What is a QR Code? Create One Free in 30 Seconds',
    description:
      'A complete guide to QR codes — what they are, how they store data, types of QR codes, and how to generate one free in seconds.',
    url: 'https://www.taskguru.online/blog/what-is-a-qr-code',
    type: 'article',
  },
};

const articleSchema = {
  '@context': 'https://schema.org',
  '@type': 'Article',
  headline: 'What is a QR Code and How Does It Work? (2026 Guide)',
  description:
    'A complete plain-English guide to QR codes — what they are, how they encode data, types, use cases, and how to generate one free online.',
  author: {
    '@type': 'Person',
    name: 'Shubham Gautam',
    url: 'https://www.taskguru.online/about',
  },
  publisher: {
    '@type': 'Organization',
    name: 'TaskGuru',
    logo: { '@type': 'ImageObject', url: 'https://www.taskguru.online/logo.png' },
  },
  datePublished: '2026-03-14',
  dateModified: '2026-03-14',
  mainEntityOfPage: {
    '@type': 'WebPage',
    '@id': 'https://www.taskguru.online/blog/what-is-a-qr-code',
  },
};

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What does QR stand for?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'QR stands for Quick Response. The name reflects the original design goal — a code that could be decoded quickly by a scanner, much faster than a traditional barcode.',
      },
    },
    {
      '@type': 'Question',
      name: 'How much data can a QR code store?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'A QR code can store up to 7,089 numeric characters, 4,296 alphanumeric characters, or 2,953 bytes of binary data. In practice, most QR codes store URLs which are typically 30–100 characters long.',
      },
    },
    {
      '@type': 'Question',
      name: 'Do QR codes expire?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Static QR codes never expire — the data is permanently encoded in the pattern. Dynamic QR codes can expire if the service hosting the redirect URL shuts down or the subscription lapses. QR codes generated by TaskGuru are static and work forever.',
      },
    },
    {
      '@type': 'Question',
      name: 'Can I scan a QR code without an app?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes. Modern smartphones can scan QR codes natively using the built-in camera app — no separate app needed. On iPhone, open the Camera app and point it at the QR code. On Android, the Camera app or Google Lens handles it automatically.',
      },
    },
    {
      '@type': 'Question',
      name: 'Are QR codes safe to scan?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'The QR code itself is safe — it is just data. However, the URL it links to may not be. Always check the URL preview that appears before tapping, and avoid scanning QR codes from unknown or suspicious sources, especially those placed over official ones in public.',
      },
    },
    {
      '@type': 'Question',
      name: 'What is the difference between a QR code and a barcode?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'A barcode is one-dimensional — it stores data in the width of vertical lines and can hold around 20 characters. A QR code is two-dimensional — it stores data horizontally and vertically, holding up to 7,089 characters and surviving up to 30% damage.',
      },
    },
  ],
};

const TOC = [
  { href: '#what-is', label: 'What Is a QR Code?' },
  { href: '#history', label: 'Who Invented the QR Code?' },
  { href: '#how-it-works', label: 'How Does a QR Code Work?' },
  { href: '#types', label: 'Types of QR Codes' },
  { href: '#use-cases', label: 'Real-World Use Cases in 2026' },
  { href: '#vs-barcode', label: 'QR Code vs Barcode' },
  { href: '#how-to-create', label: 'How to Create a QR Code for Free' },
  { href: '#safety', label: 'Are QR Codes Safe?' },
  { href: '#faq', label: 'Frequently Asked Questions' },
];

export default function BlogPost() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <div className="max-w-3xl mx-auto px-4 py-12 md:py-16">

        {/* BREADCRUMB */}
        <nav className="flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400 mb-8">
          <Link href="/blog" className="hover:text-blue-600 transition-colors font-medium">Blog</Link>
          <span>/</span>
          <span className="text-slate-700 dark:text-slate-300">What is a QR Code</span>
        </nav>

        {/* HERO */}
        <header className="mb-10">
          <div className="inline-block px-3 py-1 bg-red-100 dark:bg-red-900/40 text-red-700 dark:text-red-300 text-xs font-black uppercase tracking-wider rounded-full mb-5">
            Tech Explained
          </div>
          <h1 className="text-3xl md:text-5xl font-black text-slate-900 dark:text-white leading-tight mb-4">
            What is a QR Code?
            <span className="block text-xl md:text-2xl font-semibold text-slate-400 dark:text-slate-500 mt-2">
              How It Works, Types, Use Cases & How to Create One Free
            </span>
          </h1>
          <div className="flex flex-wrap items-center gap-3 text-sm text-slate-500 dark:text-slate-400 mb-8">
            <span>By <strong className="text-slate-700 dark:text-slate-300">Shubham Gautam</strong></span>
            <span>·</span>
            <time dateTime="2026-03-14">March 14, 2026</time>
            <span>·</span>
            <span>8 min read</span>
          </div>

          {/* Quick Answer */}
          <div className="p-5 bg-red-50 dark:bg-red-900/20 border-l-4 border-red-500 rounded-r-2xl">
            <p className="text-xs font-black text-red-600 dark:text-red-400 uppercase tracking-wider mb-2">
              ⚡ Quick Answer
            </p>
            <p className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed">
              A <strong>QR code (Quick Response code)</strong> is a two-dimensional barcode
              that stores data — usually a URL — in a grid of black and white squares. Your
              phone&apos;s camera reads the pattern and instantly opens the link, no app required.
              They can hold up to <strong>7,089 characters</strong> and never expire.
            </p>
          </div>
        </header>

        {/* TABLE OF CONTENTS */}
        <div className="mb-10 p-5 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-2xl">
          <p className="font-black text-slate-900 dark:text-white text-sm mb-3">📋 Table of Contents</p>
          <ol className="space-y-1.5">
            {TOC.map((item, i) => (
              <li key={item.href} className="flex items-center gap-2 text-sm">
                <span className="text-slate-400 font-mono text-xs w-5">{i + 1}.</span>
                <a href={item.href} className="text-blue-600 dark:text-blue-400 hover:underline">
                  {item.label}
                </a>
              </li>
            ))}
          </ol>
        </div>

        {/* BODY */}
        <div className="space-y-12 text-slate-600 dark:text-slate-400 leading-relaxed">

          {/* INTRO */}
          <div className="space-y-4 text-base">
            <p>
              You see them everywhere — on restaurant menus, product packaging, billboard
              advertisements, event tickets, and even gravestones. QR codes have gone from
              a niche industrial tool to one of the most universally recognised symbols
              in modern life.
            </p>
            <p>
              But most people have no idea how they actually work. What are those black
              squares doing? How does a phone camera read them instantly? And why can a
              damaged QR code still work perfectly? This guide answers all of it — in
              plain English.
            </p>
          </div>

          {/* SECTION 1 */}
          <section>
            <h2 id="what-is" className="text-2xl font-black text-slate-900 dark:text-white mb-4 pt-2 scroll-mt-20">
              What Is a QR Code?
            </h2>
            <p className="mb-4">
              QR stands for <strong>Quick Response</strong>. A QR code is a type of
              two-dimensional (2D) matrix barcode that stores information as a pattern of
              black squares arranged on a white grid. Unlike a traditional barcode — which
              only stores data horizontally in one direction — a QR code stores data both
              horizontally and vertically, allowing it to hold significantly more information
              in a smaller space.
            </p>
            <p className="mb-6">
              When you point your smartphone camera at a QR code, the camera reads the
              pattern, decodes it, and presents the stored information — most commonly a
              URL that it opens automatically in your browser.
            </p>

            {/* Anatomy diagram */}
            <div className="p-5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-2xl shadow-sm mb-4">
              <p className="font-black text-slate-900 dark:text-white text-sm mb-4">
                🔍 Anatomy of a QR Code
              </p>
              <div className="grid md:grid-cols-2 gap-3">
                {[
                  { name: 'Finder Patterns', desc: 'The three large squares in the corners. Tells the scanner where the code starts and its orientation — even upside down.' },
                  { name: 'Alignment Pattern', desc: 'A smaller square inside the code. Helps scanners read distorted or curved QR codes (like on a curved bottle).' },
                  { name: 'Timing Pattern', desc: 'Alternating black and white dots between the corner squares. Defines the grid size so the scanner knows how many cells to read.' },
                  { name: 'Data Modules', desc: 'The main grid of black and white squares. Each module represents a bit of data — 0 (white) or 1 (black).' },
                  { name: 'Quiet Zone', desc: 'The white border surrounding the entire code. Without it, the scanner cannot identify where the QR code ends and the background begins.' },
                  { name: 'Error Correction', desc: 'Reserved area that lets the QR code remain readable even if up to 30% of it is damaged, dirty, or covered.' },
                ].map((item) => (
                  <div key={item.name} className="flex gap-3 p-3 bg-slate-50 dark:bg-slate-800 rounded-xl">
                    <div className="w-2 h-2 rounded-full bg-red-500 flex-shrink-0 mt-1.5" />
                    <div>
                      <p className="font-bold text-slate-900 dark:text-white text-xs mb-0.5">{item.name}</p>
                      <p className="text-xs leading-relaxed text-slate-500">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {/* SECTION 2 */}
          <section>
            <h2 id="history" className="text-2xl font-black text-slate-900 dark:text-white mb-4 pt-2 scroll-mt-20">
              Who Invented the QR Code?
            </h2>
            <p className="mb-4">
              The QR code was invented in <strong>1994</strong> by <strong>Masahiro Hara</strong>,
              an engineer at Denso Wave — a subsidiary of Toyota. The original purpose had
              nothing to do with smartphones or marketing.
            </p>
            <p className="mb-6">
              Toyota&apos;s factories used traditional barcodes to track automotive parts, but
              each barcode could only hold about 20 characters. With thousands of different
              components on an assembly line, the system was slow and error-prone. Hara needed
              a code that could store more data and be scanned from any angle at high speed.
              The QR code solved both problems.
            </p>
            <div className="space-y-0">
              {[
                { year: '1994', event: 'Denso Wave (Toyota subsidiary) invents the QR code for tracking automotive parts in Japanese factories.' },
                { year: '1999', event: 'Denso Wave releases the QR code standard as open and royalty-free — anyone can use it without a licence.' },
                { year: '2002', event: 'First QR code reader app for mobile phones launches in Japan. Early adoption is mostly in Japanese media and advertising.' },
                { year: '2010', event: 'Smartphones with built-in cameras drive mainstream adoption globally. Marketing campaigns start using QR codes on posters and packaging.' },
                { year: '2020', event: 'COVID-19 accelerates adoption dramatically. Contactless menus, check-ins, and payment systems become standard worldwide.' },
                { year: '2026', event: 'QR codes are scanned over 2 billion times per day globally. Native camera scanning is built into every major smartphone OS.' },
              ].map((item, i, arr) => (
                <div key={item.year} className="flex gap-4">
                  <div className="flex flex-col items-center">
                    <div className="h-8 w-8 rounded-full bg-red-600 text-white flex items-center justify-center font-black flex-shrink-0 text-xs">
                      ●
                    </div>
                    {i < arr.length - 1 && (
                      <div className="w-0.5 bg-slate-200 dark:bg-slate-700 flex-1 my-1" style={{ minHeight: '20px' }} />
                    )}
                  </div>
                  <div className="pb-5">
                    <span className="text-xs font-black text-red-500 uppercase tracking-wider">{item.year}</span>
                    <p className="text-sm leading-relaxed mt-0.5">{item.event}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* SECTION 3 */}
          <section>
            <h2 id="how-it-works" className="text-2xl font-black text-slate-900 dark:text-white mb-4 pt-2 scroll-mt-20">
              How Does a QR Code Work?
            </h2>
            <p className="mb-6">
              Reading a QR code happens in milliseconds, but there is a sophisticated
              process happening under the hood:
            </p>
            <div className="space-y-3">
              {[
                { n: '1', color: 'bg-red-600', title: 'Camera captures the image', desc: 'Your phone camera takes a photo of the QR code. Modern cameras can read QR codes at angles up to 45 degrees and from distances of up to several metres.' },
                { n: '2', color: 'bg-orange-600', title: 'Finder patterns locate the code', desc: 'The three corner squares let the decoder instantly identify the QR code\'s position, size, and orientation — even if the image is upside down or rotated.' },
                { n: '3', color: 'bg-yellow-600', title: 'Grid mapping', desc: 'The timing patterns define the grid. The decoder maps every cell in the matrix — typically between 21×21 and 177×177 modules depending on the version.' },
                { n: '4', color: 'bg-green-600', title: 'Binary decoding', desc: 'Each black module = 1, each white module = 0. The decoder reads the data modules in a specific zigzag pattern and assembles the binary string.' },
                { n: '5', color: 'bg-blue-600', title: 'Error correction applied', desc: 'Reed-Solomon error correction checks the data integrity and repairs any corrupted modules — up to 30% damage can be recovered without losing data.' },
                { n: '6', color: 'bg-purple-600', title: 'Output delivered', desc: 'The decoded text (usually a URL) is presented to the user as a notification. Tapping it opens the link — the whole process takes under 100 milliseconds.' },
              ].map((step) => (
                <div key={step.n} className="flex gap-4 p-4 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-xl shadow-sm">
                  <div className={`h-8 w-8 rounded-full ${step.color} text-white flex items-center justify-center font-black flex-shrink-0 text-sm`}>
                    {step.n}
                  </div>
                  <div>
                    <h4 className="font-bold text-slate-900 dark:text-white text-sm mb-1">{step.title}</h4>
                    <p className="text-sm leading-relaxed">{step.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* SECTION 4 */}
          <section>
            <h2 id="types" className="text-2xl font-black text-slate-900 dark:text-white mb-4 pt-2 scroll-mt-20">
              Types of QR Codes
            </h2>
            <p className="mb-5">
              Not all QR codes work the same way. Understanding the difference helps you
              choose the right type for your use case.
            </p>
            <div className="grid md:grid-cols-2 gap-4">
              {[
                {
                  type: 'Static QR Code',
                  icon: '🔒',
                  color: 'bg-blue-50 dark:bg-blue-900/20 border-blue-100 dark:border-blue-900',
                  tc: 'text-blue-700 dark:text-blue-300',
                  pros: ['Never expires', 'No subscription needed', 'Works offline', 'Free to create'],
                  cons: ['Cannot be edited after creation', 'Cannot track scans'],
                  best: 'Personal use, business cards, permanent signage',
                },
                {
                  type: 'Dynamic QR Code',
                  icon: '🔄',
                  color: 'bg-orange-50 dark:bg-orange-900/20 border-orange-100 dark:border-orange-900',
                  tc: 'text-orange-700 dark:text-orange-300',
                  pros: ['Editable after printing', 'Tracks scan analytics', 'Can redirect to different URLs'],
                  cons: ['Requires subscription', 'Expires if service shuts down'],
                  best: 'Marketing campaigns, menus, event management',
                },
              ].map((item) => (
                <div key={item.type} className={`p-5 border rounded-2xl ${item.color}`}>
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-xl">{item.icon}</span>
                    <h3 className={`font-black ${item.tc}`}>{item.type}</h3>
                  </div>
                  <div className="space-y-3 text-sm">
                    <div>
                      <p className="text-xs font-black text-green-600 dark:text-green-400 mb-1">✓ Advantages</p>
                      <ul className="space-y-0.5">
                        {item.pros.map((p) => (
                          <li key={p} className="text-xs text-slate-600 dark:text-slate-400">• {p}</li>
                        ))}
                      </ul>
                    </div>
                    <div>
                      <p className="text-xs font-black text-red-500 mb-1">✗ Limitations</p>
                      <ul className="space-y-0.5">
                        {item.cons.map((c) => (
                          <li key={c} className="text-xs text-slate-600 dark:text-slate-400">• {c}</li>
                        ))}
                      </ul>
                    </div>
                    <div className="pt-2 border-t border-current border-opacity-20">
                      <p className="text-xs font-black text-slate-500 dark:text-slate-400">Best for: {item.best}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* SECTION 5 */}
          <section>
            <h2 id="use-cases" className="text-2xl font-black text-slate-900 dark:text-white mb-4 pt-2 scroll-mt-20">
              Real-World Use Cases in 2026
            </h2>
            <p className="mb-5">
              QR codes have expanded far beyond restaurant menus. Here is where they are
              making the biggest impact today:
            </p>
            <div className="grid md:grid-cols-2 gap-4">
              {[
                { emoji: '🍽️', title: 'Restaurants & Hospitality', desc: 'Digital menus that update in real time without reprinting. Hotel check-in and room key access via QR code.' },
                { emoji: '💳', title: 'Payments', desc: 'UPI, PhonePe, Google Pay, and WhatsApp Pay all use QR codes as the primary payment interface across India and Asia.' },
                { emoji: '📦', title: 'Product Packaging', desc: 'Brands use QR codes on packaging to link to ingredient details, sustainability reports, loyalty programmes, and how-to videos.' },
                { emoji: '🎫', title: 'Events & Ticketing', desc: 'Concert and flight tickets are QR codes. Boarding passes, conference badges, and stadium entry all use QR verification.' },
                { emoji: '📚', title: 'Education', desc: 'Textbooks embed QR codes linking to supplementary videos, quizzes, and interactive content. Teachers share assignments via QR on whiteboards.' },
                { emoji: '🏥', title: 'Healthcare', desc: 'Patient wristbands contain QR codes linking to full medical records. Vaccine certificates and prescriptions are increasingly QR-based.' },
                { emoji: '🏠', title: 'Real Estate', desc: 'Property listings on For Sale boards use QR codes to launch virtual tours, floor plans, and agent contact details instantly.' },
                { emoji: '📡', title: 'WiFi Sharing', desc: 'QR codes that automatically connect a guest to your WiFi network — no password typing required. Hotels and cafes use this extensively.' },
              ].map((item) => (
                <div key={item.title} className="flex gap-3 p-4 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-xl shadow-sm">
                  <span className="text-2xl flex-shrink-0">{item.emoji}</span>
                  <div>
                    <h3 className="font-bold text-slate-900 dark:text-white text-sm mb-1">{item.title}</h3>
                    <p className="text-xs leading-relaxed">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* CTA 1 */}
          <div className="flex flex-col sm:flex-row items-center gap-4 p-5 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-2xl">
            <div className="flex-1">
              <p className="font-bold text-slate-900 dark:text-white mb-1 text-sm">
                ⬛ Generate a Free QR Code — Instantly
              </p>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Create static QR codes for URLs, text, WiFi, and more. Free, no sign-up,
                high-resolution PNG download. Works in your browser.
              </p>
            </div>
            <Link
              href="/tools/qr-barcode-generator"
              className="flex-shrink-0 px-5 py-2.5 bg-slate-900 dark:bg-white dark:text-slate-900 hover:bg-slate-700 text-white font-bold rounded-xl transition-colors text-sm"
            >
              Create QR Code →
            </Link>
          </div>

          {/* SECTION 6 */}
          <section>
            <h2 id="vs-barcode" className="text-2xl font-black text-slate-900 dark:text-white mb-4 pt-2 scroll-mt-20">
              QR Code vs Barcode — What Is the Difference?
            </h2>
            <p className="mb-5">
              Both QR codes and barcodes store data in a visual pattern — but they are
              fundamentally different in capacity, readability, and use case.
            </p>
            <div className="overflow-x-auto rounded-2xl border border-slate-200 dark:border-slate-700 mb-5">
              <table className="w-full text-sm text-left">
                <thead className="bg-slate-900 text-white">
                  <tr>
                    <th className="p-4 font-bold">Feature</th>
                    <th className="p-4 font-bold text-red-400">QR Code</th>
                    <th className="p-4 font-bold text-slate-400">Barcode</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800 bg-white dark:bg-slate-900">
                  {[
                    ['Dimensions', '2D (horizontal + vertical)', '1D (horizontal only)'],
                    ['Data capacity', 'Up to 7,089 characters', 'Up to ~20 characters'],
                    ['Scan angle', 'Any direction, any angle', 'Must be aligned horizontally'],
                    ['Damage tolerance', 'Up to 30% damage survivable', 'Any damage = unreadable'],
                    ['Scanner required', 'Smartphone camera', 'Laser scanner or camera'],
                    ['Common use', 'URLs, payments, marketing', 'Retail products, inventory'],
                    ['Cost to create', 'Free online', 'Free online'],
                  ].map(([feature, qr, bar]) => (
                    <tr key={feature as string} className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors">
                      <td className="p-4 font-medium text-slate-900 dark:text-white">{feature as string}</td>
                      <td className="p-4 text-green-600 dark:text-green-400 font-medium">{qr as string}</td>
                      <td className="p-4 text-slate-500">{bar as string}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p className="text-sm">
              Both formats are still widely used — barcodes dominate retail product
              scanning because laser scanners are faster and cheaper at checkout counters,
              while QR codes dominate everything that requires a smartphone interaction.
            </p>
          </section>

          {/* SECTION 7 */}
          <section>
            <h2 id="how-to-create" className="text-2xl font-black text-slate-900 dark:text-white mb-4 pt-2 scroll-mt-20">
              How to Create a QR Code for Free
            </h2>
            <p className="mb-5">
              Creating a QR code takes less than 30 seconds. Here is the exact process
              using TaskGuru&apos;s free generator:
            </p>
            <div className="space-y-3 mb-6">
              {[
                { n: '1', title: 'Go to the QR Code Generator', desc: 'Open TaskGuru\'s free QR & Barcode Generator. No sign-up or account required.' },
                { n: '2', title: 'Select the QR Code tab', desc: 'The tool supports both QR codes and barcodes. Click the QR Code tab at the top.' },
                { n: '3', title: 'Enter your content', desc: 'Paste your URL, type your WiFi password, or enter any text you want to encode. The preview updates in real time.' },
                { n: '4', title: 'Customise (optional)', desc: 'Change the foreground colour and adjust the size using the slider. Larger size = better print quality for physical use.' },
                { n: '5', title: 'Download as PNG', desc: 'Click Download PNG. The file saves directly to your device at the resolution you selected. Ready for print or digital use.' },
              ].map((step) => (
                <div key={step.n} className="flex gap-4 p-4 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-xl shadow-sm">
                  <div className="h-8 w-8 rounded-full bg-slate-900 dark:bg-white dark:text-slate-900 text-white flex items-center justify-center font-black flex-shrink-0 text-sm">
                    {step.n}
                  </div>
                  <div>
                    <h4 className="font-bold text-slate-900 dark:text-white text-sm mb-1">{step.title}</h4>
                    <p className="text-sm leading-relaxed">{step.desc}</p>
                  </div>
                </div>
              ))}
            </div>
            <div className="p-5 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-2xl">
              <p className="font-black text-blue-700 dark:text-blue-300 text-sm mb-2">
                💡 Print Quality Tip
              </p>
              <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
                For business cards, set the size to at least <strong>512px</strong>. For
                banners or posters, use <strong>1024px</strong>. The QR code will remain
                perfectly sharp at any print size — no pixelation.
              </p>
            </div>
          </section>

          {/* SECTION 8 */}
          <section>
            <h2 id="safety" className="text-2xl font-black text-slate-900 dark:text-white mb-4 pt-2 scroll-mt-20">
              Are QR Codes Safe?
            </h2>
            <p className="mb-5">
              The QR code itself is just data — it cannot harm your phone. However, the
              content it links to can be dangerous. Here is how to stay safe:
            </p>
            <div className="space-y-3">
              {[
                { safe: true, text: 'Always check the URL preview that appears before tapping. Most phones show the URL before opening it — read it carefully.' },
                { safe: true, text: 'Look for HTTPS in the URL. A padlock icon means the connection is encrypted. Avoid HTTP-only links from unknown QR codes.' },
                { safe: true, text: 'Be cautious of QR codes pasted over existing ones in public places — this is a known phishing technique called "QR jacking".' },
                { safe: false, text: 'Do not scan QR codes from unexpected emails or text messages — especially ones claiming you have won a prize or need to verify your account.' },
                { safe: false, text: 'Do not scan QR codes in poorly lit areas where you cannot verify the source — fake codes placed over legitimate payment QR codes have been used in fraud.' },
              ].map((item, i) => (
                <div key={i} className={`flex gap-3 p-4 rounded-xl border ${
                  item.safe
                    ? 'bg-green-50 dark:bg-green-900/10 border-green-100 dark:border-green-900/40'
                    : 'bg-red-50 dark:bg-red-900/10 border-red-100 dark:border-red-900/40'
                }`}>
                  <span className={`font-black text-base flex-shrink-0 ${item.safe ? 'text-green-500' : 'text-red-500'}`}>
                    {item.safe ? '✓' : '✗'}
                  </span>
                  <p className="text-sm leading-relaxed">{item.text}</p>
                </div>
              ))}
            </div>
          </section>

          {/* CTA 2 */}
          <div className="p-6 bg-gradient-to-r from-slate-900 to-slate-800 text-white rounded-2xl">
            <h3 className="font-black text-lg mb-2">Create Your QR Code in 30 Seconds</h3>
            <p className="text-slate-300 text-sm mb-4">
              TaskGuru&apos;s free QR & Barcode Generator creates high-resolution static QR codes
              for URLs, WiFi, text, and more. No sign-up. No watermarks. Download PNG instantly.
            </p>
            <div className="flex flex-wrap gap-3">
              <Link
                href="/tools/qr-barcode-generator"
                className="inline-block px-5 py-2.5 bg-white text-slate-900 font-bold rounded-xl hover:bg-slate-100 transition-colors text-sm"
              >
                Create QR Code Free →
              </Link>
              <Link
                href="/tools/image-compressor"
                className="inline-block px-5 py-2.5 bg-slate-700 hover:bg-slate-600 text-white font-bold rounded-xl transition-colors text-sm"
              >
                Compress QR Image →
              </Link>
            </div>
          </div>

          {/* FAQ */}
          <section>
            <h2 id="faq" className="text-2xl font-black text-slate-900 dark:text-white mb-5 pt-2 scroll-mt-20">
              Frequently Asked Questions
            </h2>
            <div className="space-y-3">
              {faqSchema.mainEntity.map((faq, i) => (
                <details
                  key={i}
                  className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl p-5 cursor-pointer group"
                >
                  <summary className="font-bold text-slate-900 dark:text-white list-none flex justify-between items-center text-sm">
                    {faq.name}
                    <span className="transition-transform group-open:rotate-180 text-slate-400 flex-shrink-0 ml-2">▼</span>
                  </summary>
                  <p className="mt-3 text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                    {faq.acceptedAnswer.text}
                  </p>
                </details>
              ))}
            </div>
          </section>

          {/* CONCLUSION */}
          <section className="p-6 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-2xl">
            <h2 className="text-xl font-black text-slate-900 dark:text-white mb-3">
              Final Thoughts
            </h2>
            <p className="text-sm leading-relaxed mb-3">
              QR codes have come a long way from Toyota&apos;s factory floor in 1994. They are
              now a fundamental piece of digital infrastructure — connecting the physical
              world to the internet in a single camera tap.
            </p>
            <p className="text-sm leading-relaxed">
              Whether you need one for a business card, a restaurant menu, a WiFi network,
              or a product label — creating a QR code is free, takes 30 seconds, and lasts
              forever. The only rule: make sure it links somewhere worth scanning.
            </p>
          </section>

          {/* RELATED ARTICLES */}
          <div className="pt-8 border-t border-slate-200 dark:border-slate-700">
            <h3 className="text-base font-black text-slate-900 dark:text-white mb-4">
              Related Articles
            </h3>
            <div className="grid md:grid-cols-2 gap-3">
              {[
                { title: 'What is OCR? How Image to Text Technology Works', href: '/blog/what-is-ocr-image-to-text' },
                { title: 'How to Compress Images Without Losing Quality', href: '/blog/how-to-compress-images-without-losing-quality' },
                { title: 'The Rise of Local-First Web Apps in 2026', href: '/blog/local-first-web-apps-trend-2026' },
                { title: 'The Zero-Cost Tech Stack for Freelancers', href: '/blog/zero-cost-freelancer-tools' },
              ].map((post) => (
                <Link
                  key={post.href}
                  href={post.href}
                  className="p-4 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl hover:border-red-400 dark:hover:border-red-600 transition-colors group"
                >
                  <p className="font-semibold text-sm text-slate-900 dark:text-white group-hover:text-red-600 dark:group-hover:text-red-400 transition-colors">
                    {post.title} →
                  </p>
                </Link>
              ))}
            </div>
          </div>

        </div>
      </div>
    </>
  );
                }
